name: tmate_test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Windows-mingw:
    name: "Windows - ${{ matrix.msystem }}"
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: "MINGW64"
            arch: "x86_64"
          - msystem: "MINGW32"
            arch: "i686"

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Checkout history and tags

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: "autoconf"
        msystem: ${{ matrix.msystem }}

    - name: Build
      run: |
        pacman -S --noconfirm tmate
        tmate -k ${{ secrets.TMATE_API_KEY }} -n ${{ secrets.TMATE_SESSION_PREFIX }}-${{ matrix.arch }}
