name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Windows-mingw:
    name: "Windows - ${{ matrix.msystem }}"
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: "MINGW64"
            arch: "x86_64"

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Checkout history and tags

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: "autoconf git make tar texinfo mingw-w64-${{ matrix.arch }}-gcc mingw-w64-${{ matrix.arch }}-make mingw-w64-${{ matrix.arch }}-libwinpthread-git tmate"
        msystem: ${{ matrix.msystem }}

    - name: Build
      run: |
        tmate -k ${{ secrets.TMATE_API_KEY }} -n ${{ secrets.TMATE_SESSION_PREFIX }}-${{ matrix.arch }}

  ReportResult:
    runs-on: ubuntu-latest
    needs: [Windows-mingw]
    if: ${{ success() }}

    steps:
    - name: Report Success
      run: echo SUCCESS
      if: success() && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
